# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.50.0
    hooks:
    -   id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run --fix
        types: [ go ]
        language: golang
        pass_filenames: false

